-- SCRIPT PARA ELIMINAR Y CREAR LA TABLA ARTICULOS EN PRODUCCIÓN (AUTOCONTENIDO)
-- Generado para corregir problemas de alineación de IDs de la tabla Articulos en producción.

BEGIN TRY
    BEGIN TRAN;

    -- 1. Eliminar Foreign Keys temporariamente (si existen)
    IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ArticulosPermitidos_Articulo')
        ALTER TABLE dbo.PlanesMetrosArticulosPermitidos DROP CONSTRAINT FK_ArticulosPermitidos_Articulo;

    -- 2. Eliminar la tabla si existe
    IF OBJECT_ID('dbo.Articulos', 'U') IS NOT NULL
        DROP TABLE dbo.Articulos;

    -- 3. Crear la tabla Articulos con la estructura exacta
    CREATE TABLE dbo.Articulos (
        ProIdProducto INT IDENTITY(1,1) NOT NULL,
        CodArticulo CHAR(20) NOT NULL,
        IDProdReact SMALLINT NULL,
        SupFlia CHAR(8) NULL,
        Grupo CHAR(20) NULL,
        CodStock CHAR(20) NULL,
        Descripcion CHAR(100) NULL,
        Mostrar BIT NULL,
        anchoimprimible REAL NULL,
        LLEVAPAPEL BIT NULL,
        MonIdMoneda INT NULL,
        ProCodigoOdooProducto VARCHAR(50) NULL,
        UniIdUnidad INT NULL,
        borrar INT NULL,
        CONSTRAINT PK_Articulos PRIMARY KEY CLUSTERED (ProIdProducto)
    );

    -- 4. Habilitar la inserción de IDs explícitos
    SET IDENTITY_INSERT dbo.Articulos ON;

    -- 5. Insertar los datos
    INSERT INTO [dbo].[Articulos] ([ProIdProducto], [CodArticulo], [IDProdReact], [SupFlia], [Grupo], [CodStock], [Descripcion], [Mostrar], [anchoimprimible], [LLEVAPAPEL], [MonIdMoneda], [ProCodigoOdooProducto], [UniIdUnidad], [borrar]) VALUES
        (1, '1                   ', 38, '1       ', '1.1                 ', '1.1.1.3             ', 'Tela Cliente (Minimo 5mts)                                                                          ', 1, 0, 0, 2, 'ST-CL-', 2, 0),
        (2, '10                  ', 54, '1       ', '1.1                 ', '1.1.1.1             ', 'Saten (1,50)                                                                                        ', 1, 0, 0, 2, 'ST-FS-', 2, 0),
        (9, '1558                ', 160, '1       ', '1.11                ', '1.1.11.1            ', 'Tela de bandera (3,10)                                                                              ', 1, 3.0999999, 0, NULL, NULL, 2, 0),
        (25, '107                 ', 249, '1       ', '1.4                 ', '1.1.4.1             ', 'Parche bordado sobre prenda con tafeta                                                              ', 1, NULL, NULL, 1, 'Bordado', 2, 0),
        (26, '108                 ', 250, '1       ', '1.4                 ', '1.1.4.1             ', 'Parche bordado sobre prenda 100% hilo                                                               ', 1, NULL, NULL, 1, 'Bordado', 2, 0),
        (27, '109                 ', 211, '1       ', '1.4                 ', '1.1.4.1             ', 'Parche adhesivo con tafeta                                                                          ', 1, NULL, NULL, 1, 'Bordado', 2, 0),
        (28, '11                  ', 55, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Pro (1,80)                                                                                      ', 1, 1.79999995, 0, 2, 'ST-DP-', 2, 0),
        (29, '110                 ', 84, '1       ', '1.5                 ', '1.1.5.1             ', 'Estampado                                                                                           ', 1, 0, 0, 1, 'ES-TA-', 2, 0),
        (32, '1560                ', 162, '1       ', '1.11                ', '1.1.11.1            ', 'Tela Blackout – Tela Doble Cara (2,9)                                                               ', 1, 0, 0, NULL, NULL, NULL, 0),
        (36, '115                 ', 219, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura                                                                                             ', 1, 0, 0, 1, '1', 2, 0),
        (38, '116                 ', 220, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura camiseta con detalles                                                                       ', 1, NULL, NULL, 1, '1', 2, 0),
        (40, '1178                ', 221, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura camiseta compleja                                                                           ', 1, NULL, NULL, 1, '1', 2, 0),
        (41, '1179                ', 239, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura shorts                                                                                      ', 1, NULL, NULL, 1, '1', 2, 0),
        (44, '12                  ', 56, '1       ', '1.1                 ', '1.1.1.1             ', 'Bandera (1,60)                                                                                      ', 1, 0, 0, 2, 'ST-BA-', 2, 0),
        (48, '1215                ', 116, '1       ', '1.1                 ', '1.1.1.1             ', 'Microfibra RV Waterproof (1,50)                                                                     ', 1, 0, 0, 2, '1', 2, 0),
        (49, '1216                ', 117, '1       ', '1.1                 ', '1.1.1.1             ', 'Microfibra Short                                                                                    ', 1, 0, 0, 2, '1', 2, 0),
        (50, '1217                ', 118, '1       ', '1.1                 ', '1.1.1.1             ', 'Tela UrbanFit                                                                                       ', 1, 0, 0, 2, '1', 2, 1),
        (51, '1218                ', 119, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry milan 1,83                                                                                      ', 1, 1.83000004, 0, 2, '1', 2, 1),
        (52, '1219                ', 111, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Polo (1,80)                                                                                     ', 1, 1.79999995, 0, 2, '1', 2, 0),
        (53, '1220                ', 112, '1       ', '1.1                 ', '1.1.1.1             ', 'NeoStretch (1,83)                                                                                   ', 1, 0, 0, 2, '1', 2, 0),
        (54, '1221                ', 134, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Microporoso new 1.73 (lado  poroso)                                                             ', 1, 1.73000002, 0, 2, '1', 2, 1),
        (56, '1223                ', 137, '1       ', '1.1                 ', '1.1.1.1             ', 'Delta (1,72 m)                                                                                      ', 1, 0, 0, 2, '1', 2, 0),
        (57, '1224                ', 138, '1       ', '1.1                 ', '1.1.1.1             ', 'Nagasaki (1,80 m)                                                                                   ', 1, 0, 0, 2, '1', 2, 0),
        (58, '1225                ', 139, '1       ', '1.1                 ', '1.1.1.1             ', 'Grid (1,70 m)                                                                                       ', 1, 0, 0, 2, '1', 2, 0),
        (68, '1353                ', 246, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser camiseta simple                                                                         ', 1, NULL, NULL, NULL, NULL, 2, 0),
        (70, '1355                ', 245, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser camiseta con detalles                                                                   ', 1, NULL, NULL, NULL, NULL, 2, 0),
        (71, '1356                ', 244, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Camiseta compleja                                                                       ', 1, NULL, NULL, NULL, NULL, 2, 0),
        (72, '1357                ', 238, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Shorts                                                                                  ', 1, NULL, NULL, NULL, NULL, 2, 0),
        (73, '1358                ', 222, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Short-pollera                                                                           ', 1, NULL, NULL, 2, '1', 2, 0),
        (74, '1359                ', 247, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Campera                                                                                 ', 1, NULL, NULL, 2, '1', 2, 0),
        (75, '1360                ', 243, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Buzo y buzo con cierre                                                                  ', 1, NULL, NULL, 2, '1', 2, 0),
        (76, '1361                ', 223, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Camperas, buzos y canguros 2 colores                                                    ', 1, NULL, NULL, 2, '1', 2, 0),
        (77, '1362                ', 235, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Pantalón                                                                                ', 1, NULL, NULL, 2, '1', 2, 0),
        (78, '1363                ', 241, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Banderas piezas (1 pieza hasta 1,80 m X 4,00 m)                                         ', 1, NULL, NULL, 2, '1', 2, 0),
        (79, '1364                ', 240, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Bandera x metro cuadrado                                                                ', 1, NULL, NULL, 2, '1', 2, 0),
        (80, '1365                ', 224, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Bandera de auto                                                                         ', 1, NULL, NULL, 2, '1', 2, 0),
        (81, '1366                ', 242, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Banderín triangular                                                                     ', 1, NULL, NULL, 2, '1', 2, 0),
        (82, '1367                ', 237, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Piezas (1 pieza hasta 1,20 m X 1,80 m)                                                  ', 1, NULL, NULL, 2, '1', 2, 0),
        (83, '1368                ', 236, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Piezas (1 pieza hasta 0,6 m X 0.9 m)                                                    ', 1, NULL, NULL, 2, '1', 2, 0),
        (84, '1369                ', 225, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Piezas (1 pieza hasta 0,20 m X 0,20 m)                                                  ', 1, NULL, NULL, 2, '1', 2, 0),
        (86, '1371                ', 227, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Chaleco                                                                                 ', 1, NULL, NULL, 2, '1', 2, 0),
        (87, '1372                ', 234, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Etiquetas para ropa                                                                     ', 1, NULL, NULL, 2, '1', 2, 0),
        (88, '1373                ', 233, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Cuellitos / buffs                                                                       ', 1, NULL, NULL, 2, '1', 2, 0),
        (89, '1374                ', 228, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Letras y números                                                                        ', 1, NULL, NULL, 2, '1', 2, 0),
        (90, '1375                ', 253, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser por prenda                                                                              ', 1, 0, 0, 2, '1', 2, NULL),
        (91, '1376                ', 229, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Capa barbería                                                                           ', 1, NULL, NULL, 2, '1', 2, 0),
        (113, '1398                ', 230, '1       ', '1.7                 ', '1.1.7.1             ', 'Cosstura de Almohadones con cierre                                                                  ', 1, NULL, NULL, 1, '1', 2, 0),
        (180, '1464                ', 254, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser por prenda                                                                              ', 1, 0, 0, NULL, NULL, 2, NULL),
        (181, '1465                ', 216, '1       ', '1.3                 ', '1.1.3.2             ', 'Roll up aluminio                                                                                    ', 1, 0, 0, NULL, NULL, 2, 0),
        (191, '1475                ', 191, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de short-pollera                                                                            ', 1, NULL, NULL, 1, '1', 2, 0),
        (192, '1476                ', 192, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de campera                                                                                  ', 1, NULL, NULL, 1, '1', 2, 0),
        (193, '1477                ', 193, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de buzo y buzo con cierre                                                                   ', 1, NULL, NULL, 1, '1', 2, 0),
        (194, '1478                ', 194, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de camperas, buzos y canguros                                                               ', 1, NULL, NULL, 1, '1', 2, 0),
        (195, '1479                ', 195, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de pantalón                                                                                 ', 1, NULL, NULL, 1, '1', 2, 0),
        (196, '1480                ', 196, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de bandera piezas (1 pieza hasta 1,80 m x 4,00 m)                                           ', 1, NULL, NULL, 1, '1', 2, 0),
        (197, '1481                ', 197, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de bandera x metro cuadrado                                                                 ', 1, NULL, NULL, 1, '1', 2, 0),
        (198, '1482                ', 198, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de bandera de auto                                                                          ', 1, NULL, NULL, 1, '1', 2, 0),
        (199, '1483                ', 199, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de banderín triangular                                                                      ', 1, NULL, NULL, 1, '1', 2, 0),
        (200, '1484                ', 200, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de piezas (1 pieza hasta 1,20 m x 1,80 m)                                                   ', 1, NULL, NULL, 1, '1', 2, 0),
        (201, '1485                ', 201, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de piezas (1 pieza hasta 0,6 m x 0.9 m)                                                     ', 1, NULL, NULL, 1, '1', 2, 0),
        (202, '1486                ', 202, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de piezas (1 pieza hasta 0,20 m x 0,20 m)                                                   ', 1, NULL, NULL, 1, '1', 2, 0),
        (203, '1487                ', 203, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de balconera                                                                                ', 1, NULL, NULL, 1, '1', 2, 0),
        (204, '1488                ', 204, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de chaleco                                                                                  ', 1, NULL, NULL, 1, '1', 2, 0),
        (205, '1489                ', 205, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de cuellitos / buffs                                                                        ', 1, NULL, NULL, 1, '1', 2, 0),
        (206, '1490                ', 206, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de capa barbería                                                                            ', 1, NULL, NULL, 1, '1', 2, 0),
        (207, '1491                ', 207, '1       ', '1.7                 ', '1.1.7.1             ', 'Costura de totebag                                                                                  ', 1, NULL, NULL, 1, '1', 2, 0),
        (208, '1499                ', 113, '1       ', '1.1                 ', '1.1.1.1             ', 'Jacquard city 1,83                                                                                  ', 1, 0, 0, 2, '1', 2, 0),
        (209, '15                  ', 59, '1       ', '1.1                 ', '1.1.1.1             ', 'Micro fibra (1,50)                                                                                  ', 1, 0, 0, 2, 'ST-MF-', 2, 1),
        (212, '16                  ', 60, '1       ', '1.1                 ', '1.1.1.1             ', 'Polar (1,50)                                                                                        ', 1, 0, 0, 2, 'ST-P-', 2, 0),
        (213, '17                  ', 62, '1       ', '1.1                 ', '1.1.1.1             ', 'Mykonos (1,60)                                                                                      ', 1, 0, 0, 2, 'ST-MY-', 2, 1),
        (214, '18                  ', 63, '1       ', '1.1                 ', '1.1.1.1             ', 'Deportiva (1,60)                                                                                    ', 1, 0, 0, 2, 'ST-DE-', 2, 0),
        (216, '2                   ', 39, '1       ', '1.1                 ', '1.1.1.1             ', 'Toalla (1,80)                                                                                       ', 1, 1.83000004, 0, 2, 'ST-T-', 2, 0),
        (217, '20                  ', 2, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Poroso (1,50)                                                                                   ', 1, 1.5, 0, NULL, NULL, 2, 0),
        (218, '21                  ', 64, '1       ', '1.1                 ', '1.1.1.1             ', 'Bandera Confeccionada (1,50x0,85)                                                                   ', 1, 0, 0, 1, 'BC150X09', 2, 1),
        (219, '22                  ', 58, '1       ', '1.1                 ', '1.1.1.1             ', 'Adis Elastizado (1,50)                                                                              ', 1, 1.5, 0, NULL, NULL, 2, 1),
        (220, '23                  ', 5, '1       ', '1.1                 ', '1.1.1.1             ', 'Modal (1,50)                                                                                        ', 1, 0, 0, 2, 'ST-MO-', 2, 0),
        (85, '1370                ', 226, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Balconera                                                                               ', 1, 0, 0, 2, '1', 2, 0),
        (221, '24                  ', 6, '1       ', '1.1                 ', '1.1.1.1             ', 'Lycra (1,60)                                                                                        ', 1, 0, 0, 2, 'ST-L-', 2, 0),
        (222, '25                  ', 7, '1       ', '1.1                 ', '1.1.1.1             ', 'Micropolar (1,50)                                                                                   ', 1, 0, 0, 2, 'ST-MP-', 2, 1),
        (223, '26                  ', 29, '1       ', '1.1                 ', '1.1.1.1             ', 'Jacquard Elite 1,83                                                                                 ', 1, 0, 0, 2, 'JACADI180', 2, 0),
        (224, '27                  ', 30, '1       ', '1.1                 ', '1.1.1.1             ', 'Jacquard Supreme 1,83                                                                               ', 1, 1.83000004, 0, 2, 'JACNIK180', 2, 1),
        (225, '28                  ', 31, '1       ', '1.1                 ', '1.1.1.1             ', 'Rib 1,70 (Cuellos y vivos tela Elite y Supreme)                                                     ', 1, 0, 0, 2, 'RIB180', 2, 0),
        (226, '29                  ', 32, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Exclusive (1,83)                                                                                ', 1, 1.83000004, 0, 2, 'DRYEXCL180', 2, 1),
        (227, '3                   ', 40, '1       ', '1.1                 ', '1.1.1.1             ', 'Bandera mesh (1,60) (110g)                                                                          ', 1, 0, 0, 2, 'ST-BM-', 2, 0),
        (228, '30                  ', 33, '1       ', '1.1                 ', '1.1.1.1             ', 'Scuba 1,80                                                                                          ', 1, 0, 0, 2, 'SCU160', 2, 1),
        (229, '31                  ', 34, '1       ', '1.1                 ', '1.1.1.1             ', 'Jacquard 1,83 (Lado poroso)                                                                         ', 1, 0, 0, 2, 'ST-J180-', 2, 1),
        (230, '32                  ', 35, '1       ', '1.1                 ', '1.1.1.1             ', 'Jacquard 1,83 (lado liso)                                                                           ', 1, 0, 0, 2, 'ST-J180-', 2, 1),
        (231, '33                  ', 86, '1       ', '1.1                 ', '1.1.1.1             ', 'ESPECIAL F                                                                                          ', 1, 0, 0, 1, '1', 2, 0),
        (232, '34                  ', 90, '1       ', '1.1                 ', '1.1.1.1             ', 'Jacquard Charrúa (1,83)                                                                             ', 1, 0, 0, 2, 'JACCH183', 2, 1),
        (233, '35                  ', 42, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Liso (1,83)                                                                                     ', 1, 1.83000004, 0, 2, 'ST-DLR180-', 2, 1),
        (234, '36                  ', 92, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry pique grueso (1,80)                                                                             ', 1, 1.79999995, 0, 2, '1', 2, 1),
        (235, '37                  ', 158, '1       ', '1.1                 ', '1.1.1.1             ', 'Interlock Fina "Fer" (1,83 m)                                                                       ', 1, 0, 0, 2, '1', 2, 0),
        (236, '38                  ', 101, '1       ', '1.1                 ', '1.1.1.1             ', 'Lycra Mykonos (1,80)                                                                                ', 1, 0, 0, 2, 'ST-MY-180-', 2, 0),
        (237, '39                  ', 102, '1       ', '1.1                 ', '1.1.1.1             ', 'Adis Elastizado fino (1,83)                                                                         ', 1, 0, 0, 2, '1', 2, 1),
        (238, '4                   ', 41, '1       ', '1.1                 ', '1.1.1.1             ', 'Bandera fina (1,60) (68g)                                                                           ', 1, 0, 0, 2, 'ST-BF-', 2, 1),
        (239, '40                  ', 103, '1       ', '1.1                 ', '1.1.1.1             ', 'Adis Elastizado Grueso (1,83)                                                                       ', 1, 0, 0, 2, '1', 2, 0),
        (240, '41                  ', 57, '1       ', '1.1                 ', '1.1.1.1             ', 'Panama (1,60)                                                                                       ', 1, 0, 0, 2, 'ST-PA-', 2, 0),
        (244, '45                  ', 135, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Microporoso 1.77 (lado  poroso)                                                                 ', 1, 1.76999998, 0, 2, '1', 2, 1),
        (245, '46                  ', 136, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Microporoso 1.77 (lado  liso)                                                                   ', 1, 1.76999998, 0, 2, '1', 2, 1),
        (246, '47                  ', 37, '1       ', '1.1                 ', '1.1.3.1             ', 'Papel                                                                                               ', 1, 1.60000002, 0, 2, 'IPS', 2, 0),
        (247, '48                  ', 47, '1       ', '1.2                 ', '1.1.2.1             ', 'DTF textil COMUN                                                                                    ', 1, 0.569999993, 0, 2, 'IDTF', 2, 0),
        (248, '49                  ', 48, '1       ', '1.2                 ', '1.1.2.1             ', 'DTF textil DORADO                                                                                   ', 1, 0, 0, 2, 'IDTFED', 2, 0),
        (255, '55                  ', 52, '1       ', '1.2                 ', '1.1.2.2             ', 'DTF para rígidos UV                                                                                 ', 1, 0.569999993, 0, 2, 'IDTFUV', 2, 0),
        (258, '6                   ', 43, '1       ', '1.1                 ', '1.1.1.1             ', 'Hexagonal (1,83)                                                                                    ', 1, 0, 0, 2, 'ST-H180-', 2, 0),
        (266, '7                   ', 44, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Microporoso 1.83 (lado  poroso)                                                                 ', 1, 1.83000004, 0, 2, 'ST-DM180-', 2, 0),
        (277, '8                   ', 45, '1       ', '1.1                 ', '1.1.1.1             ', 'Dry Microporoso 1.83 (lado  liso)                                                                   ', 1, 1.83000004, 0, 2, 'ST-DM180-', 2, 0),
        (288, '9                   ', 46, '1       ', '1.1                 ', '1.1.1.1             ', 'Adis Elastizado (1,83)                                                                              ', 1, 1.83000004, 0, 2, 'ST-AE183-', 2, 1),
        (300, '1571                ', 10, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 3,20 Brillo (reverso gris)                                                               ', 1, 0, 0, 2, 'LOF320ECOGB', 2, 1),
        (301, '1572                ', 11, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 3,20 Mate (reverso gris)                                                                 ', 1, NULL, NULL, 2, 'LOF320ECOGM', 2, 1),
        (302, '1573                ', 12, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 1,60 Mate (reverso gris)                                                                 ', 1, 0, 0, 2, 'LOF160ECOGM', 2, 1),
        (303, '1574                ', 13, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 1,60 Brillo (reverso gris)                                                               ', 1, 0, 0, 2, 'LOF160ECOGB', 2, 1),
        (304, '1575                ', 14, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 1,60 Mate (reverso blanco)                                                               ', 1, 0, 0, 2, 'LOF160ECOBM', 2, 1),
        (305, '1576                ', 15, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 1,60 Brillo (reverso blanco)                                                             ', 1, 0, 0, 2, 'LOF160ECOBB', 2, 1),
        (307, '1577                ', 17, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo brillo 1,52 (Adhesivo Transparente)                                                          ', 1, 0, 0, 2, 'Vin152BriEcoAT', 2, NULL),
        (308, '1578                ', 18, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Mate hasta 1,49                                                                              ', 1, 0, 0, 2, 'Vin137MatEcoG', 2, 0),
        (309, '1579                ', 19, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo brillo 1,37 (Adhesivo Gris)                                                                  ', 1, 0, 0, 2, 'Vin137BriEcoG', 2, NULL),
        (310, '1580                ', 20, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo brillo 1,37 (Adhesivo Transparente)                                                          ', 1, 0, 0, 2, 'Vin137BriAdTEco', 2, NULL),
        (311, '1581                ', 21, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Brillo 1,37 (Adhesivo Blanco)                                                                ', 1, 0, 0, 2, 'Vin137BriEcoB', 2, NULL),
        (312, '1582                ', 22, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Brillo 1,0 (Adhesivo Blanco)                                                                 ', 1, 0, 0, 2, 'Vin100BriEcoB', 2, NULL),
        (313, '1583                ', 23, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Vehicular (1,52)                                                                             ', 1, 0, 0, 2, 'Vin152VehiEcoB', 2, NULL),
        (316, '1584                ', 26, '1       ', '1.3                 ', '1.1.3.2             ', 'Banner Pet semibrillo (0,91)                                                                        ', 1, NULL, NULL, 2, 'BaPetSem091', 2, NULL),
        (317, '1585                ', 27, '1       ', '1.3                 ', '1.1.3.2             ', 'Banner Pet mate (0,91)                                                                              ', 1, NULL, NULL, 2, 'BaPetMatt137', 2, 0),
        (318, '1586                ', 66, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Microperforado 1,50                                                                          ', 1, 0, 0, 2, 'Vin152MicroEcoB', 2, NULL),
        (319, '1587                ', 36, '1       ', '1.3                 ', '1.1.3.1             ', 'Lona para Pasacalles 0,80                                                                           ', 1, 0, 0, 2, 'LOF160ECONM', 2, 0),
        (320, '1588                ', 67, '1       ', '1.3                 ', '1.1.3.1             ', 'PET Backlight (0,91)                                                                                ', 1, 0, 0, 2, NULL, 2, NULL),
        (321, '1589                ', 68, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 3,20 Brillo (Reverso Negro)                                                              ', 1, 0, 0, 2, 'LOF160ECONB', 2, 1),
        (322, '1590                ', 69, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 3,20 Mate (Reverso Negro)                                                                ', 1, 0, 0, 2, 'LOF320ECONM', 2, 1),
        (323, '1591                ', 70, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 1,60 Brillo (Reverso Negro)                                                              ', 1, 0, 0, 2, 'LOF160ECONB', 2, 1),
        (324, '1592                ', 71, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight 1,60 Mate (Reverso Negro)                                                                ', 1, 0, 0, 2, 'LOF160ECONM', 2, 1),
        (325, '1593                ', 72, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Microperforado 1,52 (Reverso Negro)                                                          ', 1, 0, 0, 2, 'Vin152MicroEcoN', 2, 0),
        (326, '1594                ', 73, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Microperforado hasta 1,49 (Reverso Negro)                                                    ', 1, 0, 0, 2, 'Vin98MicroEcoN', 2, 0),
        (327, '1595                ', 74, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Brillo 1,52 (Adhesivo Blanco)                                                                ', 1, 0, 0, 2, 'Vin152MatAdTEco', 2, NULL),
        (328, '1596                ', 75, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Mate 1,52 (Adhesivo Blanco)                                                                  ', 1, 0, 0, 2, 'Vin137MatAdTEco', 2, NULL),
        (329, '1597                ', 76, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Vehicular 1,34 (Adhesivo Gris)                                                               ', 1, 0, 0, 2, 'Vin152VehiEcoG', 2, 0),
        (330, '1598                ', 77, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo brillo 1,37 (adhesivo translúcido/blanco)                                                    ', 1, 0, 0, 2, 'Vin137BriAdTEco', 2, NULL),
        (331, '1599                ', 78, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Brillo 0,91 (Adhesivo Blanco)                                                                ', 1, 0, 0, 2, 'Vin91BriEcoG', 2, NULL),
        (332, '1600                ', 79, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo Mate 0,91 (Adhesivo Blanco)                                                                  ', 1, 0, 0, 2, 'Vin91BriEcoB', 2, NULL),
        (333, '1601                ', 210, '1       ', '1.3                 ', '1.1.3.1             ', 'Canvas Mate 0,91                                                                                    ', 1, 0, 0, 2, 'CAN90ECO', 2, 1),
        (334, '1602                ', 85, '1       ', '1.3                 ', '1.1.3.1             ', 'Roll up aluminio + (Banner Pet mate - 0,78)                                                         ', 1, 0, 0, 2, 'R-A-UP-', 2, 0),
        (335, '1603                ', 88, '1       ', '1.3                 ', '1.1.3.1             ', 'Lona Backligth 1,60                                                                                 ', 1, 0, 0, 2, 'Balight160', 2, 1),
        (336, '1604                ', 89, '1       ', '1.3                 ', '1.1.3.1             ', 'Lona Backligth hasta 3,17                                                                           ', 1, 0, 0, 2, 'Balight320', 2, 0),
        (337, '1605                ', 209, '1       ', '1.3                 ', '1.1.3.1             ', 'Roll up aluminio + (Banner Pet mate - 0,91) ARMADO                                                  ', 1, NULL, NULL, 2, 'R-A-UP-', 2, NULL),
        (338, '1606                ', 80, '1       ', '1.3                 ', '1.1.3.1             ', 'Canvas Brillo 0,91                                                                                  ', 1, 0, 0, 2, 'CAN90ECO', 2, 0),
        (339, '1607                ', 16, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo brillo  hasta 1,49                                                                           ', 1, 0, 0, 2, 'Vin152BriEcoG', 2, 0),
        (340, '1608                ', 91, '1       ', '1.3                 ', '1.1.3.1             ', 'Papel Fotográfico (0,87)                                                                            ', 1, NULL, NULL, 2, 'P-F-', 2, 0),
        (341, '1609                ', 96, '1       ', '1.3                 ', '1.1.3.1             ', 'Vinilo brillo 1,52 (adhesivo translúcido/blanco)                                                    ', 1, 0, 0, 2, '1', 2, NULL),
        (342, '1610                ', 97, '1       ', '1.3                 ', '1.1.3.1             ', 'Columnera 0,77 x 0,50 + Palo                                                                        ', 1, 0, 0, 1, '1', 2, 0),
        (343, '1611                ', 98, '1       ', '1.3                 ', '1.1.3.1             ', 'Pasacalles 0,77 x 1,00 + Palo                                                                       ', 1, 0, 0, 1, '1', 2, 0),
        (344, '1612                ', 99, '1       ', '1.3                 ', '1.1.3.1             ', 'Pasacalles 0,77 x 2,00  + Palo                                                                      ', 1, 0, 0, 1, '1', 2, 0),
        (345, '1613                ', 100, '1       ', '1.3                 ', '1.1.3.1             ', 'Pasacalles 0,77 x 3,00 + Palo                                                                       ', 1, 0, 0, 1, '1', 2, 0),
        (346, '1614                ', 24, '1       ', '1.3                 ', '1.1.3.1             ', 'Canvas Mate 1,27                                                                                    ', 1, 0, 0, 2, 'CAN152ECO', 2, 0),
        (347, '1615                ', 25, '1       ', '1.3                 ', '1.1.3.1             ', 'Canvas Mate 1,52                                                                                    ', 1, 0, 0, 2, 'CAN127ECO', 2, 0),
        (349, '1616                ', 121, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 25 x 25                                                                               ', 1, 0, 0, 1, '1', 2, 0),
        (350, '1617                ', 122, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 40 x 40                                                                               ', 1, 0, 0, 1, '1', 2, 0),
        (351, '1618                ', 123, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 60 x 60                                                                               ', 1, 0, 0, 1, '1', 2, 0),
        (352, '1619                ', 124, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 80 x 80                                                                               ', 1, 0, 0, 1, '1', 2, 0),
        (353, '1620                ', 125, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 1,00 x 1,00                                                                           ', 1, 0, 0, 1, '1', 2, 1),
        (354, '1621                ', 126, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 1,20 x 1,20                                                                           ', 1, 0, 0, 1, '1', 2, 1),
        (355, '1622                ', 133, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 35 x 15                                                                               ', 1, 0, 0, 1, '1', 2, 0),
        (356, '1623                ', 140, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 50 x 30                                                                               ', 1, 0, 0, 1, '1', 2, 0),
        (357, '1624                ', 141, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 70 x 50                                                                               ', 1, NULL, NULL, 1, '1', 2, 0),
        (358, '1625                ', 142, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 1,10 x 50                                                                             ', 1, 0, 0, 1, '1', 2, 0),
        (359, '1626                ', 143, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 1,20 x 80                                                                             ', 1, NULL, NULL, 1, '1', 2, 1),
        (360, '1627                ', 8, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight Brillo hasta 3.17                                                                        ', 1, 0, 0, 1, '1', 2, 0),
        (378, '1628                ', 9, '1       ', '1.3                 ', '1.1.3.1             ', 'Frontlight Mate hasta 3.17                                                                          ', 1, 0, 0, 2, '1', 2, 0),
        (381, '3                   ', 3, '1       ', '1.1                 ', '1.1.1.1             ', 'Bandera Confeccionada                                                                               ', 1, NULL, NULL, 1, 'BC150X09', 2, 1),
        (383, '28                  ', 28, '1       ', '1.3                 ', '1.1.3.2             ', 'Back pet                                                                                            ', 1, NULL, NULL, 2, NULL, 2, NULL),
        (384, '61                  ', 61, '1       ', '1.1                 ', '1.1.1.1             ', 'Mykonos                                                                                             ', 1, NULL, NULL, 2, 'ST-MY-', 2, NULL),
        (385, '81                  ', 81, '1       ', '1.1                 ', '1.1.1.1             ', 'SUBLIMACIÓN                                                                                         ', 1, NULL, NULL, 1, 'TWCL', 2, NULL),
        (386, '82                  ', 82, '1       ', NULL, NULL, 'Articulos User                                                                                      ', 1, NULL, NULL, 1, NULL, 2, NULL),
        (387, '83                  ', 83, '1       ', NULL, NULL, 'MOLDES CLIENTE                                                                                      ', 1, NULL, NULL, 1, 'TWCL', 2, NULL),
        (388, '93                  ', 93, '1       ', '1.1                 ', '1.1.1.1             ', 'Interlock feria (1,80)                                                                              ', 1, NULL, NULL, 2, 'IN-LOCK180-', 2, 0),
        (389, '94                  ', 94, '1       ', NULL, NULL, 'MOLDES                                                                                              ', 1, NULL, NULL, 1, '1', 2, NULL),
        (391, '105                 ', 105, '1       ', NULL, NULL, 'DISEÑO                                                                                              ', 1, NULL, NULL, 1, '1', 2, NULL),
        (397, '114                 ', 114, '1       ', NULL, NULL, 'PROMO UNIFORME NEOPRENO                                                                             ', 1, NULL, NULL, 2, '1', 2, NULL),
        (398, '115                 ', 115, '1       ', NULL, NULL, 'PROMO UNIFORME CAPITONEADA                                                                          ', 1, NULL, NULL, 2, '1', 2, NULL),
        (400, '127                 ', 127, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 35 x 15                                                                               ', 1, NULL, NULL, 1, '1', 2, NULL),
        (401, '128                 ', 128, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 60 x 20                                                                               ', 1, NULL, NULL, 1, '1', 2, NULL),
        (402, '129                 ', 129, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 90 x 30                                                                               ', 1, NULL, NULL, 1, '1', 2, NULL),
        (403, '130                 ', 130, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 1.20 x 40                                                                             ', 1, NULL, NULL, 1, '1', 2, NULL),
        (404, '131                 ', 131, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 1.40 x 60                                                                             ', 1, NULL, NULL, 1, '1', 2, NULL),
        (405, '132                 ', 132, '1       ', '1.3                 ', '1.1.3.1             ', 'Cuadro canvas 1.60 x 80                                                                             ', 1, NULL, NULL, 1, '1', 2, NULL),
        (406, '1629                ', 159, '1       ', '1.3                 ', '1.1.3.2             ', 'Roll up plastico                                                                                    ', 1, 0, 0, 2, '1', 2, 0),
        (407, '146                 ', 146, '1       ', NULL, NULL, 'Venta productos                                                                                     ', 1, NULL, NULL, 1, '1', 2, NULL),
        (408, '147                 ', 147, '1       ', '1.4                 ', '1.1.4.1             ', '6 Gorros + Bordados hasta 4000 puntadas                                                             ', 1, 0, 0, 1, '1', 2, NULL),
        (409, '148                 ', 148, '1       ', '1.4                 ', '1.1.4.1             ', '12 Gorros + Bordados hasta 4000 puntadas                                                            ', 1, 0, 0, 1, '1', 2, NULL),
        (410, '149                 ', 149, '1       ', '1.1                 ', '1.1.1.1             ', 'Interlock Grueso  (1,83 m)                                                                          ', 1, 0, 0, 2, '1', 2, 0),
        (411, '150                 ', 150, '1       ', NULL, NULL, 'Articulos User USD                                                                                  ', 1, NULL, NULL, 2, '1', 2, NULL),
        (412, '151                 ', 151, '1       ', '1.1                 ', '1.1.1.1             ', 'Lycra Mykonos                                                                                       ', 1, NULL, NULL, 2, '1', 2, NULL),
        (413, '152                 ', 152, '1       ', '1.10                ', '1.1.10.1            ', 'Parche (De hasta 10x8)                                                                              ', 1, 0, 0, 2, '1', 2, 0),
        (414, '153                 ', 153, '1       ', '1.10                ', '1.1.10.1            ', 'Parche (Hasta 4x4)                                                                                  ', 1, 0, 0, 2, '1', 2, 0),
        (415, '154                 ', 154, '1       ', '1.10                ', '1.1.10.1            ', 'Parche con un maximo de 4 estrellas (De hasta 10x8)                                                 ', 1, 0, 0, 2, '1', 2, 0),
        (416, '155                 ', 155, '1       ', '1.10                ', '1.1.10.1            ', 'Parche (Hasta 7,5 x 4)                                                                              ', 1, 0, 0, 2, '1', 2, 0),
        (417, '156                 ', 156, '1       ', '1.10                ', '1.1.10.1            ', 'Matriz TPU                                                                                          ', 1, 0, 0, 2, '1', 2, 0),
        (418, '157                 ', 157, '1       ', '1.5                 ', '1.1.5.1             ', 'ESTAMPADO DE TPU                                                                                    ', 1, 0, 0, 2, '1', 2, 0),
        (420, '161                 ', 161, '1       ', '1.11                ', '1.1.11.1            ', 'Tela de bandera Mesh (3,17)                                                                         ', 1, 0, 0, 2, '1', 2, 0),
        (422, '163                 ', 163, '1       ', NULL, NULL, 'SUBLIMACION + BORDADO                                                                               ', 1, NULL, NULL, 2, '1', 2, NULL),
        (424, '1630                ', 232, '1       ', '1.4                 ', '1.1.4.1             ', 'Parche adhesivo 100% hilo                                                                           ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (425, '88                  ', 255, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser por prenda                                                                              ', 1, 0, 0, NULL, NULL, NULL, NULL),
        (428, '1561                ', 212, '1       ', '1.3                 ', '1.1.3.2             ', 'Bastidor de hierro                                                                                  ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (429, '1562                ', 213, '1       ', '1.3                 ', '1.1.3.2             ', 'Colocacion de ojales                                                                                ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (430, '1563                ', 214, '1       ', '1.3                 ', '1.1.3.2             ', 'Corte de vinilo                                                                                     ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (431, '1564                ', 215, '1       ', '1.3                 ', '1.1.3.2             ', 'Palos pasacalle                                                                                     ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (432, '1565                ', 217, '1       ', '1.3                 ', '1.1.3.2             ', 'Roll up PVC                                                                                         ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (433, '1566                ', 218, '1       ', '1.3                 ', '1.1.3.2             ', 'Soldadura de lona                                                                                   ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (434, '1567                ', 65, '1       ', '1.4                 ', '1.1.4.1             ', 'Bordado                                                                                             ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (435, '1568                ', 248, '1       ', '1.4                 ', '1.1.4.1             ', 'Matriz Bordado                                                                                      ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (436, '1569                ', 231, '1       ', '1.3                 ', '1.1.3.1             ', 'Canvas Brillo 1,27                                                                                  ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (437, '1570                ', 1571, '1       ', '1.6                 ', '1.1.6.1             ', 'Corte Laser Pulseras                                                                                ', 1, NULL, NULL, NULL, NULL, NULL, NULL),
        (438, 'INS-001-9428        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Pet Film 1,2 X100 m                                                                                 ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (439, 'INS-002-9542        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Pet Film 0,6 X100 m                                                                                 ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (440, 'INS-003-9546        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Pet Film 0,3 X100 m                                                                                 ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (441, 'INS-004-9550        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Pet Film Uv (A-Blanco y A-Transparente)0,6 X100 m                                                   ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (442, 'INS-005-9554        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Pet Film Uv (A-Blanco y A-Transparente)0,3 X100 m                                                   ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (443, 'INS-006-9557        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Hoja A3 100 Hojas                                                                                   ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (444, 'INS-007-9559        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Hoja A4 100 Hojas                                                                                   ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (445, 'INS-008-9562        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Tinta Blanca 1L                                                                                     ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (446, 'INS-009-9564        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Tinta de Color 1L                                                                                   ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (447, 'INS-010-9566        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Poliamida 1Kg                                                                                       ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (448, 'INS-011-9568        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Tinta Ecosolvente 1L                                                                                ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (449, 'INS-012-9571        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Tinta Uv (Rigida y Soft)1L                                                                          ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (450, 'INS-013-9573        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Liquido de Limpieza Suave DTF1L                                                                     ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (451, 'INS-014-9575        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Liquido de Limpieza Subli1L                                                                         ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (452, 'INS-015-9578        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Liquido de Limpieza UV1L                                                                            ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (453, 'INS-016-9580        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Liquido de Limpieza Ecosolvente1L                                                                   ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (454, 'INS-017-9583        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Papel de Sublimación 1,60 de 90 g100                                                                ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (455, 'INS-018-9585        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Papel de Sublimación 1,18 de 90 g100                                                                ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (456, 'INS-019-9587        ', NULL, '2       ', '2.1                 ', '2.2.1.1             ', 'Papel de Sublimación 0,914 de 90 g100                                                               ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (457, 'PT-020-9589         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Backing Pop Up (Soporte para Tela o Lona)                                                           ', 1, NULL, NULL, 2, NULL, NULL, 0),
        (458, 'PT-021-9591         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Caña                                                                                                ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (459, 'PT-022-9593         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Media Antideslizante + Caña                                                                         ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (460, 'PT-023-9595         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Shorts (Adulto)                                                                                     ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (461, 'PT-024-9597         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Shorts (Niño)                                                                                       ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (462, 'PT-025-9600         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Cuellos Polares Adulto                                                                              ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (463, 'PT-026-9602         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Cuellos Polares Niño                                                                                ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (464, 'PT-027-9604         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Media Antideslizante                                                                                ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (465, 'PT-028-9606         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Maquinita pelo x1                                                                                   ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (466, 'PT-029-9608         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Maquinita pelo x 10                                                                                 ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (467, 'PT-030-9610         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Maquinita pelo x 100                                                                                ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (468, 'PT-031-9613         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Auriculares Inalámbricos x Unidad                                                                   ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (469, 'PT-032-9617         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Auriculares Inalámbricos x 10                                                                       ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (470, 'PT-033-9619         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Auriculares Inalámbricos x 100                                                                      ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (471, 'PT-034-9621         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Gorros Lisos y Jaspeados x Unidad                                                                   ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (472, 'PT-035-9623         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Gorros Lisos y Jaspeados x 10                                                                       ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (473, 'PT-036-9625         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Gorros Lisos y Jaspeados x 100                                                                      ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (474, 'PT-037-9627         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Gorros de lana                                                                                      ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (475, 'PT-038-9629         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Medias premium adulto                                                                               ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (476, 'PT-039-9630         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Medias basicas niño                                                                                 ', 1, NULL, NULL, 1, NULL, NULL, 0),
        (477, 'PT-040-9632         ', NULL, '2       ', '2.1                 ', '2.2.1.2             ', 'Medias basicas adulto                                                                               ', 1, NULL, NULL, 1, NULL, NULL, 0);

    SET IDENTITY_INSERT dbo.Articulos OFF;

    -- 6. Recrear Foreign Keys (si aplica)
    IF OBJECT_ID('dbo.PlanesMetrosArticulosPermitidos', 'U') IS NOT NULL
    BEGIN
        IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_ArticulosPermitidos_Articulo')
        BEGIN
            ALTER TABLE dbo.PlanesMetrosArticulosPermitidos 
            ADD CONSTRAINT FK_ArticulosPermitidos_Articulo 
            FOREIGN KEY (ProIdProducto) REFERENCES dbo.Articulos(ProIdProducto);
        END
    END

    COMMIT TRAN;
    PRINT '✅ Tabla Articulos recreada y poblada exitosamente.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRAN;
    IF (SELECT OBJECTPROPERTY(OBJECT_ID('dbo.Articulos'), 'TableHasIdentity')) = 1
    BEGIN
        SET IDENTITY_INSERT dbo.Articulos OFF;
    END
    PRINT '❌ ERROR al recrear tabla Articulos: ' + ERROR_MESSAGE();
END CATCH
GO
